version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.springframework.boot
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: com.auth0:java-jwt
    versions:
    - 3.12.0
    - 3.12.1
    - 3.13.0
    - 3.14.0
  - dependency-name: org.jooq:jooq
    versions:
    - 3.14.6
    - 3.14.7
    - 3.14.8
  - dependency-name: org.jooq:jooq-codegen
    versions:
    - 3.14.6
    - 3.14.7
    - 3.14.8
  - dependency-name: org.jooq:jooq-meta
    versions:
    - 3.14.6
    - 3.14.7
    - 3.14.8
  - dependency-name: org.postgresql:postgresql
    versions:
    - 42.2.18
    - 42.2.19
  - dependency-name: nu.studer.jooq
    versions:
    - "5.2"
  - dependency-name: org.apache.commons:commons-lang3
    versions:
    - "3.11"
